version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "4000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/www:/usr/share/nginx/html
    networks:
      - node-network
  hello-node:
    build: .
    networks:
      - node-network

networks:
  node-network:
    name: hello-node-network
