version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/www:/usr/share/nginx/html
    networks:
      - node-network
  hello-node:
    build: .
    networks:
      - node-network

networks:
  node-network:
    name: hello-node-network
